- hosts: localhost # Master Node  
  vars:
    home_dir: /home/vagrant
  roles:
  - docker
  - kubernetes
  - master 

- hosts: worker1
  roles:
  - docker
  - kubernetes 
  - worker 

- hosts: worker2 
  roles:
  - containerd
  - kubernetes
  - worker 
  
# Addons -- Optional
- hosts: localhost
  roles:
  - addons 
